'use strict'

// A request summary as `requests.list`, `requests.cancel` and `requests.remind`
// return it (docs/external-api.md § Requests): no answers, no timeline.
const REQUEST_SUMMARY_OUTPUT_FIELDS = [
  { key: 'id', label: 'Request ID', type: 'string' },
  { key: 'status', label: 'Status', type: 'string' },
  { key: 'outcome', label: 'Outcome', type: 'string' },
  { key: 'formId', label: 'Form ID', type: 'string' },
  { key: 'submissionId', label: 'Submission ID', type: 'string' },
  { key: 'isTest', label: 'Test Request', type: 'boolean' },
  { key: 'recipient__email', label: 'Recipient Email', type: 'string' },
  { key: 'recipient__name', label: 'Recipient Name', type: 'string' },
  { key: 'language', label: 'Language', type: 'string' },
  { key: 'externalId', label: 'External ID', type: 'string' },
  { key: 'metadata', label: 'Metadata', dict: true },
  { key: 'context', label: 'Context', dict: true },
  { key: 'delivery', label: 'Delivery', type: 'string' },
  { key: 'deliveryStatus', label: 'Delivery Status', type: 'string' },
  { key: 'expiresAt', label: 'Expires At (ms)', type: 'number' },
  { key: 'createdAt', label: 'Created At (ms)', type: 'number' },
  { key: 'completedAt', label: 'Completed At (ms)', type: 'number' },
  { key: 'expiredAt', label: 'Expired At (ms)', type: 'number' },
  { key: 'canceledAt', label: 'Canceled At (ms)', type: 'number' },
  { key: 'cancelReason', label: 'Cancel Reason', type: 'string' },
  { key: 'remindersSent', label: 'Reminders Sent', type: 'integer' },
]

const SAMPLE_REQUEST_SUMMARY = {
  id: 'req_example000000000000',
  workspaceId: 'ws_abc123',
  formId: 'form_abc123',
  formSnapshotId: 'snap_abc123',
  submissionId: null,
  status: 'pending',
  outcome: null,
  createdVia: 'api',
  isTest: false,
  recipient: { email: 'ada@example.com', name: 'Ada Lovelace' },
  language: 'en',
  externalId: 'run-42',
  metadata: { runId: 'run-42' },
  context: { case_id: 'CASE-9' },
  prefill: { company_name: 'Acme' },
  readonlyKeys: ['company_name'],
  documents: [],
  delivery: 'email',
  deliveryStatus: 'sent',
  hasCallback: false,
  callbackFailedAt: null,
  expiresAt: 1782388800000,
  createdAt: 1779796800000,
  updatedAt: 1779796800000,
  openedAt: null,
  startedAt: null,
  lastActivityAt: null,
  completedAt: null,
  expiredAt: null,
  canceledAt: null,
  canceledBy: null,
  cancelReason: null,
  reminderStep: 0,
  remindersSent: 0,
  reminderDueAt: null,
  dataPurgedAt: null,
}

const REQUEST_ID_INPUT_FIELD = {
  key: 'requestId',
  label: 'Request ID',
  type: 'string',
  required: true,
  helpText: 'The Request ID from a Create Request step, a Find Request step or a request trigger.',
}

module.exports = { REQUEST_SUMMARY_OUTPUT_FIELDS, SAMPLE_REQUEST_SUMMARY, REQUEST_ID_INPUT_FIELD }
